### ISSUE TITLE
実行順に関する根拠とTips

### ISSUE THREAD

**Issue by PalmNeko** [PalmNeko/minishell#13]
環境変数の設定などのタイミングに関する根拠を議論する場所

**Comment by PalmNeko** [comment]
**環境変数の設定場所はリダイレクション処理のあと**
**根拠**
コマンド: 
```HAPPY_CAT=nyao cat  << EOF
> $HAPPY_CAT
> EOF
```
出力結果:
```

```
ヒアドク前に変数が設定されているなら、変数展開が発生して、HAPPY_CATの値が`nyao`として出力されるはず。
つまり、変数展開が発生しているのは、ヒアドクの後である。

**Comment by nytsdayo** [comment]
<<EOF　だと実行はできるけどヒアドク自体は標準出力に表示する機能がない？
```
~$ HAPPY_CAT=hogehoge
~$ <<EOF
> $HAPPY_CAT
> EOF

rnakatan@c4r1s9:~$ cat <<EOF
> $HAPPY_CAT
> EOF
hogehoge

rnakatan@c4r1s9:~$ <<EOF
> hogeta
> EOF

rnakatan@c4r1s9:~$ cat <<EOF
> cat
> EOF
cat

```

**Comment by nytsdayo** [comment]
やっと理解できたかも！！！
 ```
$> HAPPY_CAT=nyao echo $HAPPY_CAT $? > outfile | cat -e outfile
0$
$> HAPPY_CAT=nyao echo $HAPPY_CAT $?
0
~$ HAPPY_CAT=nyao | echo $HAPPY_CAT

~$ HAPPY_CAT=nyao | echo "$HAPPY_CAT" a
 a

```

**Comment by nytsdayo** [comment]
bashのmanより

単純なコマンドの展開
単純なコマンドを実行すると、シェルは以下に示す展開、代入、 リダイレクションを左から右の順で実行します。
1.
パーザが変数代入 (コマンド名の前にあるもの) またはリダイレクションと判断した単語は、 保存されて後で処理されます。
2.
変数代入でもリダイレクションでもない単語が展開されます。 もし展開の後に残っている単語があれば、 その最初の単語がコマンド名となり、残りが引き数となります。
3.
リダイレクションが前述の リダイレクト で説明したように実行されます。
4.
変数代入の = の後にあるテキストに対して、チルダ展開、 パラメータ展開、コマンド置換、算術式展開、クォート削除が行われます。 この処理は変数を代入する前に行われます。

**Comment by PalmNeko** [comment]
fork, ヒアドク, ファイルオープン, コマンドのパス解決の順番
1. ヒアドク
2. fork
3. ファイルオープン
4. コマンドのパス解決

**ヒアドクが先、ファイル判定が後**, **forkが先、ファイルオープンが後**
> 1つ目のコマンドに存在しないファイルを指定しても、２つ目のコマンドが実行される
`aaaaa`ファイルは存在しないが`file`は存在する。

コマンド
```
echo 'test' > file
catowefoijs << EOF < aaaaa | cat < file
ewoij
EOF
```
出力
```
test
-bash: aaaaa: No such file or directory
```

**ファイルの判定が先、コマンドのパス解決が後**
> 存在しないコマンドと存在しないファイルを指定した場合、コマンドの判定が行われない

コマンド
```
ehoc < aaaaa
```
出力
```
-bash: aaaaa: No such file or directory
```

**Comment by PalmNeko** [comment]
ボーナスをやる場合のみですが、「展開」、コマンドの実行は単純コマンドごとに実行する前に処理する。

コマンド
```
A=321
A=123 && echo $A
A=321 echo $A
```
出力
```
123
123
```

**Comment by PalmNeko** [comment]
ヒアドクの入力を促すのはコマンド全体の実行前だが、
ヒアドクで変数展開するときは、前回のリストを実行した後に処理される。

各リストを実行する直前にヒアドクの変数展開を行う。

コマンド
```
 A=333 && echo 'test' && cat << EOF
$A
EOF
```
出力
```
test
333
```
> 最初のリストで設定した変数が、最後のリストのヒアドクで実行されている。

また、straceコマンドを使って次のように、実行するとヒアドクの変数展開が子プロセスで行われていることもわかる。

コマンド
```sh
strace -f -o trace -e write bash -c "echo \$\$ && echo 'test' < oiweoisd | cat <<EOF
\${}
EOF"
```
出力
```
201840
bash: line 1: oiweoisd: No such file or directory
bash: line 1: ${}
: bad substitution
```
作成された、traceファイルの中身
```
201840 write(1, "201840\n", 7)          = 7
201841 write(2, "bash: line 1: oiweoisd: No such "..., 50) = 50
201841 +++ exited with 1 +++
201842 write(2, "bash: line 1: ${}\n", 18) = 18
201842 write(2, ": bad substitution\n", 19) = 19
201842 +++ exited with 1 +++
201840 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=201841, si_uid=0, si_status=1, si_utime=0, si_stime=0} ---
201840 +++ exited with 1 +++
```
> PIDが201840 が最初のコマンドのプロセスIDで、201841 が2個目、201842 が３個目である。
ヒアドキュメントのエラー文が３個目のプロセスIDで表示されていることから、子プロセスでヒアドキュメントの変数展開をしていることがわかる。

**Comment by PalmNeko** [comment]
単数コマンドか複数コマンドか、ビルトインかビルトインではないかでforkするかどうかを判断しているようである。
面倒なので些細な挙動の違いについては無視することにした。
