### ISSUE TITLE
設計 > データ構造

### ISSUE THREAD

**Issue by nytsdayo** [PalmNeko/minishell#3]
- [ ] 必要なデータの洗い出し

- [ ] minishellそのもので使うデータの洗い出し
- [ ] 文法解析時に使うデータの洗い出し

**Comment by nytsdayo** [comment]
そもそも環境変数はプロセスによって独立したものをもつので、外部変数environで取得した環境変数を持っておけば良さそう
exportやunsetの時に使うenvironもこの時取得したものを使う・・・認識です

**Comment by nytsdayo** [comment]
minishell用 BNF 例
ref : 入門bash 第２版

<letter> ::= [a-z] | [A-Z]
<digit> ::= [0-9]
<number> ::= <digit> | <number><digit>
<word> ::= <letter> | <word><letter> | <word> '_'
<word_list> ::= <word> | <word_list><word>
<assignment_word> ::= <word> '=' <word>
<redirection> ::= '>' <word> | '<' <word> | '>>' <word> | '<<' <word>
<simple_command_element> ::= <word> | <assigmennt_word> | <redirection>
<redirection_list> ::= <redirection> | <redirection_list><redirection>
<simple_command> ::= <simple_command_element> | <simple_command><simple_command_element>
<command>::= <simple_command>
<newline_list> ::= '' | <newline_list> '\n'
<pipline_command> ::= <pipline>
<pipeline> ::= <pipeline> '|' <newline_list><pipeline> | <command>

---
for bonus
<subshell> ::= '(' <compound_list> ')'
<group_command> ::= '(' <list> ')'
<list1> ::= <list1> '&&' <newline_list><list1> | <list1> '||' <newline_list><list1>

**Comment by nytsdayo** [comment]
環境変数の中にシェル変数と言われてるものをすべてぶち込んで管理出来たらベスト？

**Comment by PalmNeko** [comment]
```
name=[value] ...
```
の構文を採用するので、環境変数とシェル変数は別の方がいいと思います。
ただし、シェル変数はコマンドで使用する一部のものだけで問題ないと思います。

**Comment by nytsdayo** [comment]
初期化に統合します
