### ISSUE TITLE
Dockerコンテナ内でのデバッグについて。

### ISSUE THREAD

**Issue by PalmNeko** [PalmNeko/minishell#45]
現状では、lldbをインストールしても、デバッグはできない。
ソース：https://stackoverflow.com/questions/70108775/gdb-exits-immediately-process-finished-with-exit-code-1-or-lldb-a-packet-ret/70108776#70108776

`run_container.sh`のdocker runのオプションに、以下のオプションを追加すると、lldbでデバッグできるようになる。
```
		--cap-add=SYS_PTRACE		--security-opt		seccomp=unconfined
```

lldbを追加して実行可能にするために、修正予定はある。

**Comment by nytsdayo** [comment]
こちら確認しました！
デバッガーを使ったデバッグはまだ必要無さそう（基本的にプリントデバッグの人間なので）なので優先度低めでも大丈夫です🙆
