### ISSUE TITLE
設計 >> 字句解析

### ISSUE THREAD

**Issue by nytsdayo** [PalmNeko/minishell#6]

**Comment by PalmNeko** [comment]
# 呼び出し順序イメージ
```mermaid
flowchart TD
    readline[入力]
    %% --> is_variable{変数代入？}
    --> tokenize[字句解析]
    --> wildcard_expansion[ワイルドカード展開]
    --> parse[構文解析]
    --> expansion[変数展開]
    --> trim[クォーテーション削除]
```
# 命名規則
(一旦勝手につけてるだけなので、あってもなくてもいいです！)
* minishell用に作成された関数であることを示すため、組み込みとの違いを明確にするために、接頭語`ms_`を付ける。

**Comment by PalmNeko** [comment]
> 設計の形式に関して、タイトル、宣言、説明、戻り値、[エラー]を基本に、拡張したり縮小したりする予定。

# ms_tokenize 字句解析

入力された文字列を、各トークン（字句）ごとに分割して返す。

## 宣言
`t_list *tokenize(const char *readline_text)`

## 説明
処理要件に従って、トークンに分割する。
トークンはメモリにコピーされる。
戻り値は、必要に応じて`destroy_token_list`関数を使って解放する必要がある。

readline_textは、入力されたコマンド。

## 処理要件
引数 readline_textに対して以下の要件に従って、スペースを除く、トークンをすべてとりだす。

* 文字列(TK_STRING)は、"か'で囲まれている部分か特殊文字と空白以外から成る。間に空白が無ければ一つの文字列として扱う。
* `|` は、パイプトークン(TK_PIPE)として扱う。
* `[n]('>>'|'<'|'>')`は、リダイレクトトークン(TK_REDIRECT)として扱う。(ｎは数値のみで構成される。)
* `[n]<<[-]`は、ヒアドクトークン(TK_HEREDOC)として扱う。
* `&& ||`は、リストトークン(TK_LIST)として扱う。
## 戻り値

成功時、t_token型の値を取るリスト。
失敗時、NULL。errnoにエラー番号が設定される。

## エラー
組み込み関数で発生したエラーをそのままerrnoに渡される。つまり、errnoにおいて特に処理を行わない。

## 型定義
**宣言**
```
typedef enum e_token_type t_token_type;
typedef struct s_token t_token;

enum e_token_type {
    TK_STRING,
    TK_PIPE,
    TK_REDIRECT,
    TK_HEREDOC
};

struct s_token {
    t_token_type type,
    const char *str,
}
```

**e_token_type**
| 要素名 | 内容 |
| -- | -- |
| TT_STRING | 文字列 |
| TT_PIPE | パイプ(\|) |
| TT_REDIRECT | リダイレクト(>> > <) |
| TT_HEREDOC | ヒアドク(<<) |
| TK_LIST | リスト(&& \|\|)

**s_token**
| 識別子 | 意味|
| -- | -- |
| type | トークンの種類 |
| str | トークンがメモリにコピーされた文字列の先頭アドレス |

## 例
各番号は、戻り値のリストを前から順に表示したものである。
```c
tokenize("");
1. {.type=TK_STRING, .str=""}
```
```c
tokenize("a");
1. {.type=TK_STRING, .str="a"}
```
```c
tokenize("echo 'a <file");
1. {.type=TK_STRING, .str="echo"}
2. {.type=TK_STRING, .str="'a <file"}
```
```c
tokenize("echo \"$abc\"");
1. {.type=TK_STRING, .str="echo"}
2. {.type=TK_STRING, .str="'\"$abc\""}
```
```c
tokenize("< file1 echo >file2 a0<file3 abcdef");
1. {.type=TK_REDIRECT, .str="<"}
2. {.type=TK_STRING, .str="file1"}
3. {.type=TK_STRING, .str="echo"}
4. {.type=TK_REDIRECT, .str=">"}
5. {.type=TK_STRING, .str="file2"}
6. {.type=TK_STRING, .str="a0"}
7. {.type=TK_REDIRECT, .str="<"}
8. {.type=TK_STRING, .str="file3"}
9. {.type=TK_STRING, .str="abcdef"}
```
```c
tokenize(" echo \"a\"'b'c 0>file2");
1. {.type=TK_STRING, .str="echo"}
2. {.type=TK_STRING, .str="\"a\"'b'c"}
3. {.type=TK_REDIRECT, .str="0>"}
4. {.type=TK_STRING, .str="file2"}
```
```c
tokenize(" echo \"a\"'b'c 0<<-file2");
1. {.type=TK_STRING, .str="echo"}
2. {.type=TK_STRING, .str="\"a\"'b'c"}
3. {.type=TK_HEREDOC, .str="0<<-"}
4. {.type=TK_STRING, .str="file2"}
```
```c
tokenize("VAR=123 \"BAR\"=321 echo VAR=123");
1. {.type=TK_STRING, .str="VAR=123"}
2. {.type=TK_STRING, .str="\"BAR\"=321"}
3. {.type=TK_STRING, .str="echo"}
4. {.type=TK_STRING, .str="VAR=123"}
```

# ms_destroy_token_list
t_token型の値を取るリストのメモリを開放する。

## 宣言
`void ms_destroy_token_list(t_list *tk_lst);`
> メモリ開放系は、`void (void *ptr)`の形に型変換できるようにしておくと、関数ポインタが使えて何かと便利。

## 説明
tk_lstをすべて開放する。
tk_lstがNULLだった場合何もしない。

## 戻り値
なし

## エラー
なし

**Comment by PalmNeko** [comment]
スペースもトークンとして扱った方が楽な気がしてきた。

**Comment by PalmNeko** [comment]
構文解析でコードがあまりにも複雑になりそうだったため、字句解析をもっと細かくすることにした。
前段階として有限オートマトンで表してみる。
色々参考になったことやつぶやきなどなど↓


字句解析に置いて、有限オートマトンと言われるものが使用されるらしく、また字句解析に使用できそうなため、これを利用する。
[wiki 字句解析](https://ja.wikipedia.org/wiki/%E5%AD%97%E5%8F%A5%E8%A7%A3%E6%9E%90)
[字句解析に関する説明がわかりやすい](http://p-www.iwate-pu.ac.jp/~wjh/lectures/lctp/chap-3.pdf)

また、数字から数値へのトークン化に置いて、字句解析中に数値化するようなので、それを視野に入れて設計を見直す。
[実際のコードがわかりやすい](https://atmarkit.itmedia.co.jp/ait/articles/0705/15/news135_3.html)

ネットに乗っているほとんどの字句解析や構文解析は簡単なものが多い気がする‥‥？
字句解析をより丁寧に行って、構文解析の簡略化に進む。

頭の中が整理できないので、空白のトークン化も行う。

有限オートマトンを作成した。（字句解析に使う状態遷移とトークン化のタイミングを以下のグラフで示す。）

ここでは、meta文字は次のうちのどれかを指すものとする：'<' '<<' '<<-' '>' '>>' ' ' '=' '&&' '||'
ここでは、簡単のためリストは作成していないが、実際の設計時には含める予定。
また、「受理」の段階でトークン化する予定。受理できないものはトークン化しないor失敗

数値
```mermaid
stateDiagram-v2
	[*] --> number: 0~9
	number --> number: 0~9
	number --> 受理（例：01、123）: 数字以外
```

識別子
```mermaid
stateDiagram-v2

	[*] --> pre_identify: _
	pre_identify --> identify: a-z, A-Z, _
	pre_identify --> word: (a-z, A-Z, 0-9) 以外

	[*] --> identify: a-z, A-Z
	identify --> identify: a-z, A-Z, 0-9
	identify --> 受理: (a-z, A-Z, 0-9) 以外
```

ワード
```mermaid
stateDiagram-v2
	[*] --> word: not-meta
	word --> word: not-meta
	word --> 受理: meta文字

```

リダイレクション
```mermaid
stateDiagram-v2
	[*] --> number: 0-9
	number --> number: 0-9
	number --> 拒否: オーバーフロー
	number --> redirection: <, >
	redirection --> 受理: 以外
	redirection --> 受理: '>'
	redirection --> heredoc: <
	heredoc --> 受理: '-'
	heredoc --> 受理: 以外
```

文字列リテラル(シングルクウォート)
```mermaid
stateDiagram-v2
	[*] --> single_quote: " ' "
	single_quote --> single_quote: " ' " 以外
	single_quote --> 受理: " ' "
```

ダブルクォート
```mermaid
stateDiagram-v2
	[*] --> 受理: ' " '
```

変数
(カッコ内は、本家では変数として扱うが、今回は扱わないもの)
```mermaid
stateDiagram-v2
	[*] --> assignment_start: $
	assignment_start --> 受理: ?, (0-9), (#), ($), (!), (@) (*), (_)
	assignment_start --> assignment_bracket_start: {
	assignment_bracket_start --> inner_bracket: a-z, A-Z, 0-9
	inner_bracket --> inner_bracket: a-z, A-Z, 0-9
	inner_bracket --> 受理: }
	assignment_bracket_start --> 受理: }
	assignment_start --> assignment: a-z, A-Z
	assignment --> assignment: a-z, A-Z, 0-9
	assignment --> 受理: 以外
```

パイプ
```mermaid
stateDiagram-v2
	[*] --> 受理: |
```

区切り文字
```mermaid
stateDiagram-v2
	[*] --> separate: '\n', '\t', ' '
	separate --> separate: '\n', '\t', ' '
	separate --> 受理: 以外
```
