### ISSUE TITLE
構文解析

### ISSUE THREAD

**Issue by nytsdayo** [PalmNeko/minishell#7]

**Comment by PalmNeko** [comment]
字句解析は、名詞、助詞などの品詞に分けることだとしたら、構文解析は、主語や述語などの成分に分けることらしい。
minishell的に、構文解析は、リダイレクション、コマンド、リスト（&& ||）、ヒアドク.etc...に分類することだと思った。

**Comment by PalmNeko** [comment]
構文解析と意味解析について少し認識がずれていた。
```
A=123
```
と
```
"A"=123
```
、
```
#=123
```
は構文的には問題がない。そして、両方ともおそらく構文解析的にassignment_wordに分類するのが適切。
しかし、意味としては、上が代入で、中央がコマンドになり、一番下は何もしない。
構文はあくまでもトークン一覧を木構造に格納して間違っているかどうかを判定するものっぽい・・・？
つまり、後から意味が変わることがあるっぽい。

**Comment by PalmNeko** [comment]
構文解析は、展開の前に行うようでした。
というのも、各パイプラインを実行する前に変数展開や実行を行っているようです。
大きく修正入ります。

**Comment by PalmNeko** [comment]
次のプルリクで作成完了
https://github.com/PalmNeko/minishell/pull/15
