### ISSUE TITLE
終了

### ISSUE THREAD

**Issue by nytsdayo** [PalmNeko/minishell#9]

**Comment by nytsdayo** [comment]
# minishellの終了処理

## 終了条件
①exitコマンドの実行
②EOFの受信

### ms_cleanup_and_exit(int status)
- **説明** 
	- 終了時に各種メモリの解放を行ったのち引数に指定されたステータスで終了を行う。
	- 解放するメモリは初期化パートで動的に確保したメモリを対象とする。
	
終了処理について、検討した結果上記のようになりました。
どうでしょうか？改善の必要がなさそうであればこのままmainブランチに直接作成しようと思っています。

**Comment by PalmNeko** [comment]
大丈夫だと思います！
